class Strings {
  static const String UYGULAMA_ADI = "Oyun Rehberi";
  static const List<String> OYUN_ADLARI = [
    "Witcher 3",
    "CsGO",
    "Gta5",
    "Fifa 21",
    "Ets 2",
    "Forza",
    "Hitman",
    "Rocket league",
    "Pubg",
    "NBA2K21",
  ];
  static const List<String> OYUN_HAKKINDA = [
    "\tOYUN HAKKINDAKİ BİLGİLER\n\n"
        "\tThe Witcher 3: Wild Hunt, serinin diğer oyunları gibi Geralt of Rivia'nın hikâyesini konu alıyor. İkinci oyunun sonunda yaşanan olayların üzerinden altı ay geçer ve Geralt'ın hafızası yerine gelir. Hafızasını geri kazanan Geralt, kayıp aşkı Yennefer'ı aramaya başlar. Ardından Ciri'yi geri getirmek için Emhyr var Emreis'den hayatının en büyük kontratını alır ancak bu hiç kolay olmayacaktır çünkü Ciri'nin peşinde Wild Hunt vardır.\n\n",
    "\tOYUN HAKKINDAKİ BİLGİLER\n\n"
        "\tCounter Strike Global Offensive: Oyun, Teröristler ve Anti-Teröristler adlı takımı Her iki taraf da birbirlerini yok etmeleriyle ve aynı zamanda ayrı hedefleri tamamlamakla görevlidir. Teröristler, oyun moduna bağlı olarak ya bombayı yerleştirmeli ya da rehineleri savunmalıdır; Anti Teröristler ise ya bombanın yerleştirilmesini önlemeli, bombayı etkisiz hale getirmeli ya da rehineleri kurtarmalıdır.\n\n",
    "\tOYUN HAKKINDAKİ BİLGİLER\n\n"
        "\tGtaV : Rockstar North tarafından geliştirilen ve Rockstar Games tarafından yayımlanan video oyunu. Grand Theft Auto serisinin yedinci ana oyunudur. İlk olarak 17 Eylül 2013 tarihinde PlayStation 3 ve Xbox 360 için piyasaya çıkmıştır. Seride bir ilk olarak oyunda üç ana karakter bulunmaktadır: Michael De Santa, Trevor Philips ve Franklin Clinton.\n\n",
    "\tOYUN HAKKINDAKİ BİLGİLER\n\n"
        "\tFIFA21: Electronic Arts tarafından geliştirilen ve aynı şirketinin yayımcılığını yaptığı spor simülasyon video oyunudur. Dünyanın dört bir yanından 17.000’den fazla futbolcu, 700’den fazla takım, 90’dan fazla stadyum ve 30’dan fazla lig oyunda bulunmaktadır. \n\n",
    "\tOYUN HAKKINDAKİ BİLGİLER\n\n"
        "\tEuro Truck Simulator 2 :SCS Software tarafından çıkarılmış olan bir kamyon simülasyonudur. 19 Ekim 2012'de Microsoft Windows için çıkmış olan oyun günümüz Avrupa'sını temel almıştır.\n\n",
    "\tOYUN HAKKINDAKİ BİLGİLER\n\n"
        "\tForza Horizon 4:  2018 yılında Playground Games tarafından geliştirilen ve Microsoft Studios tarafından yayınlanan bir yarış video oyunudur. Oyun, Forza Horizon serisinin dördüncü oyunu olup 2 Ekim 2018 tarihinde Microsoft Windows ve Xbox One için piyasaya sürüldü.\n\n",
    "\tOYUN HAKKINDAKİ BİLGİLER\n\n"
        "\tHitman 2: IO Interactive tarafından geliştirilen ve Warner Bros. Interactive Entertainment tarafından Microsoft Windows, PlayStation 4, Xbox One ve Stadia (Hitman: World of Assassination adı altında)  13 Kasım 2018'de yayınlanan gizlilik oyunudur. Hitman oyunu serisindeki büyük taksit ve World of Assassination üçlemesinin ikinci girişi, 2016'daki Hitman'ın devamı olarak sunulmuştur. Hitman'da başlayan olay örgüsüne devam eden tek oyunculu hikaye, Providence olarak bilinen dünya işlerini kontrol eden gizli örgütü yok etmeye çalışan müttefiklerinin peşine düşen genetiği değiştirilmiş suikastçı Ajan 47'yi yönetmekteyiz. Ancak Gölge Müşteri'nin kimliğini keşfettikten sonra, o ve idarecisi Diana Burnwood taraf değiştirir ve ona Providence liderlerini bulmasında yardımcı olur\n\n",
    "\tOYUN HAKKINDAKİ BİLGİLER\n\n"
        "\tRocket League: Psyonix tarafından geliştirilen ve yayınlanan, arabalarla oynanan bir futbol oyunudur. İlk olarak Microsoft Windows ve PlayStation 4 platformları için Temmuz 2015'te piyasaya sürüldü. 2016 yılında Xbox One için geliştirilen sürüm yayınlandı. Rocket League, OS X ve Linux için beta sürümlerini yayınlamaya hala devam etmekte. 505 Games firması, Haziran 2016'dan beri PlayStation 4 ve Xbox One platformları için oyunun fiziksel olarak dağıtımını üstlenmiştir. Futbol'un roket destekli arabalarla daha eğlenceli olduğunu savunan oyun ister tek kişilik, ister çevrimiçi olarak oynanabiliyor. Her takım en az 1, en fazla 4 kişilik olabiliyor.\n\n",
    "\tOYUN HAKKINDAKİ BİLGİLER\n\n"
        "\tPlayerUnknown's Battlegrounds ya da bilinen adıyla PUBG: Bluehole tarafından yayımlanan ve geliştirilmekte olan çok oyunculu bir video oyunudur. Oyunda 100'e yakın (en fazla 100) oyuncu rotası belirlenmiş bir uçağın içinde oyuna başlarlar. İstedikleri zaman uçaktan atlarlar ve paraşütleriyle adanın herhangi bir konumuna inerler. Oyuncuların temel amacı çeşitli yerlerden buldukları çeşitli silahlarla diğer oyuncuları öldürüp ölmeden en sona kalan oyuncu olmaktır. Oyun esnasında adanın haritasındaki güvenli alan gittikçe küçülmeye başlar. Harita küçüldükçe oyuncular daha küçük bir alana yoğunlaşırlar ve birbirlerini görüp saf dışı bırakmaları ihtimâli kolaylaşır. Oyunda en son hayatta kalan oyuncu/takım oyunu kazanır.\n\n",
    "\tOYUN HAKKINDAKİ BİLGİLER\n\n"
        "\tNBA 2K21: Visual Concepts tarafından geliştirilen ve 2K Sports tarafından yayınlananmış bir basketbol video oyunudur.\n\n",
  ];

  static const List<String> OYNANIS = [
    "\tOYNANIŞ HAKKINDAKİ BİLGİLER\n\n"
        "\tWild Hunt'ın haritası, önceki oyunlarına göre yaklaşık 30 kat daha büyüktür. Ayrıca bir başka açık dünya oyunu olan Grand Theft Auto V'dan ise 1.5 kat büyüktür. Haritanın bir ucundan diğer ucuna at ile gitmek yaklaşık 40 dakika sürmektedir. Oyunda at, tekne kullanma şansına ya da Fast-Travel adı verilen hızlı seyahat yapma imkânı da vardır. Bu sayede oyuncular önceden gittikleri bölgelere zaman kaybetmeden hızlı bir şekilde gidebilecekler. Oyunun senaryo kısmı 50 saat sürmekle beraber yan görevlerle birlikte bu süre 100 saat olmakta. Oyuncunun verdiği kararlara göre oyun 3 farklı şekilde son buluyor. Ayrıca yine oyuncunun verdiği kararlara göre oyun toplam 36 farklı şekilde değişiyor.\n\n",
    "\tOYNANIŞ HAKKINDAKİ BİLGİLER\n\n"
        "\tSerinin önceki oyunları gibi Global Offensive, görev tabanlı birçok oyunculu birinci şahıs nişancı oyunudur. Oyuncular ilk önce görevleri tamamlamak veya düşman takımı yok etmek için teröristler veya terörle mücadele ekibi takımlarından birini seçerler. Örneğin, yıkım haritalarında (de_) teröristler bomba kurmaya çalışırken, terörle mücadele bombanın kurulmasını engellemeye veya kurulmuş bombayı imha etmeye çalışır. Global Offensive'e önceki oyunlardaki görevlere ek olarak silah yarışı (arms race) denilen bir mod eklenmiş, bu modla birlikte klasik Counter-Strike haritalarının yanında farklı haritalar da oyuna dahil edilmiştir.\n\n",
    "\tOYNANIŞ HAKKINDAKİ BİLGİLER\n\n"
        "\tAçık uçlu aksiyon-macera oyunudur. Önceden de belirttiğimiz gibi oyunda 3 adet ana karakteri yönetebilmekteyiz.Oyuncular karakterler arasında geçiş yapabilme imkanına sahiplerdir.Oyunda tekne kullanabilme, uçuş yarışlarına ve off-road yarışmalarına katılma, paraşütle atlayış, akrobasi, yoga, triatlon yapma, tenis oynama ve golf oynama gibi etkinlik ve hobi faaliyetleri mevcuttur.\n\n ",
    "\tOYNANIŞ HAKKINDAKİ BİLGİLER\n\n"
        "\t 4 ayrı oyun modu bulunmaktadır. VOLTA FOOTBALL modu, futbolu özüne döndüren bir oyun modudur. Yepyeni ekipmanlarla Avatarınızı oluşturup dünyanın dört bir yanında çeşitli az oyunculu futbol formatlarının oynandığı 20’den fazla futbol sahasında tarzınızı yansıtırken, arkadaşlarınızla birlikte sokakların ruhunu da yaşayacaksınız. FIFA Ultimate Team (FUT) modu, FIFA’nın en popüler modudur. Kariyer modu maçlar, transferler ve antrenman özellikleriyle takımınızı yönettiğiniz bir moddur. Özel kurallar modunda farklı kural setlerini uygulayan veya hiçbir kuralın uygulanmadığı maçlar yapabilirsiniz. \n\n",
    "\tOYNANIŞ HAKKINDAKİ BİLGİLER\n\n"
        "\tEuro Truck Simulator 2 :Oyuncu kendine ilk önce bir profil açar. Burada ismini,şirket ismini,tercih ettiği çekiciyi,resmini ve şirketin logosunu seçer. Daha sonra başlama şehri seçer ve tercih ettiği çekici ile küçük bir sefer yapar. Bundan sonra bankadan kredi ve şirketlerden iş teklifi gelir ve oyuncu oyunu oynamaya başlar.\n\n",
    "\tOYNANIŞ HAKKINDAKİ BİLGİLER\n\n"
        "\tOyun, Birleşik Krallık'ın kurgusal temsili bölgelerinde geçmektedir ve 450'den fazla lisanslı araç sunmaktadır. Oyun, oyuncuların kendi yarışlarını yaratmalarını sağlayan bir pist yaratıcısına sahiptir. Oyun, her sunucu 72 oyuncuya kadar desteklenerek, öncekilerden gelen AI güdümlü 'drivatarlara' kıyasla, senkronize paylaşılan bir dünyada geçmektedir ve seriye değişen mevsimleri tanıtmasıyla dikkat çekmektedir. Oyun, çevrimdışı modda da oynanabilir.Forza Horizon 4, Metacritic'e göre, Xbox One sürümü için evrensel beğeni alırken, PC sürümü genellikle olumlu incelemeler aldı. Haziran 2019 tarihi itibarı ile oyun 10 milyon kullanıcıya sahiptir.\n\n",
    "\tOYNANIŞ HAKKINDAKİ BİLGİLER\n\n"
        "\tHitman 2'nin oynanışı, bir aksiyon-macera gizli tabanlı oyun olan önceki serideki oyunlarla benzerdir. Oyuncular, Uluslararası Sözleşme Ajansı (ICA) için çalışan sözleşmeli bir suikastçi olan Agent 47'yi, yüksek profilli suçlu hedefleri ortadan kaldırmak için dünyanın çeşitli yerlerine seyahat ederken üçüncü şahıs bakış açısıyla kontrol ediyor. Oyun, farklı yerlerde belirlenen sekiz görev içeriyor. Özetle, oyunun görevleri (sırayla) Yeni Zelanda'daki Hawke's Bay'de gerçekleşir; Miami'de bir yarış pistinde; Kolombiya'daki kurgusal Santa Fortuna köyü; Mumbai'nin kenar mahalleleri; Whittleton Creek'in kurgusal Vermont banliyösü; ve Kuzey Atlantik'te bir yerlerde kurgusal Sgàil Adası. Oyunun indirilebilir içeriği New York City'deki kurgusal Milton-Fitzpatrick bankasını ve Maldivler'deki hayali Haven Island tatil beldesini tanıtıyor. Oyun, bir NPC'yi bilinçsiz hale getirmek için kullanılabilen sarsıcı gadget'lar sunar ve oyuncunun keskin nişancı tüfeği gibi büyük silahları şüphe uyandırmadan halka açık yerlerde gizlemesine ve taşımasına olanak tanıyan evrak çantasını bulunmaktadır. Oyunun duyurusuna, Hitman 2'nin ön siparişini verenlere hemen sunulan Sniper Assassin adlı çok oyunculu mod piyasaya sürüldü. Bu mod, oyun çıktığında Hitman 2'nin tüm kopyalarıyla birlikte geldi. Bu modda oyuncular, belirli bir süre içinde keskin nişancı tüfeği kullanarak hedefleri ortadan kaldırmakla görevlidir. Ajan 47'ye ek olarak oyuncular, her ikisi de benzersiz cephane türlerine erişebilen ICA ajanları Knight ve Stone olarak da oynayabilirler. Bu modun çevrimiçi çok oyunculu özelliğinin, Hitman 3'ün piyasaya sürülmesinden bir noktada, diğer çok oyunculu mod olan Hayalet Modunun 31 Ağustos 2020'de çevrimdışı duruma getirilmesiyle birlikte oyundan kaldırılması planlanıyor. Oyunun önceki sürümünde olduğu gibi, Hitman 2, zaman sınırlı  görevlerine sahiptir. İngiliz aktör Sean Bean, oyundaki ilk Elusive Target'ı canlandırıyor.\n\n",
    "\tOYNANIŞ HAKKINDAKİ BİLGİLER\n\n"
        "\tRocket League'in oynanışı, selefi Supersonic Acrobatic Rocket-Powered Battle-Cars ile büyük ölçüde aynı. Oyuncular, roketle çalışan bir arabayı kontrol eder ve bir yıkım derbisini anımsatan unsurlarla, iç mekan futbolunu andıran bir şekilde gol atmak için diğer takımın kale alanına doğru arabalardan çok daha büyük bir topa vurmak için kullanırlar. Oyuncuların arabaları havadayken topa vurmak için zıplama özelliğine sahiptir. Oyuncular ayrıca, arabalarını sahadaki işaretli alanların üzerinden geçirerek, hızlı bir şekilde sahayı geçmelerini, topa vurmak için eklenen momentumu kullanmalarını veya başka bir oyuncunun arabasına çarparak onu yok etmelerini sağlayarak hız artışı elde edebilirler; İkinci durumda, yok edilen araba, sahanın kendi takımının tarafında birkaç saniye sonra yeniden doğar. Bir oyuncu, havada uçarken kendisini ileriye doğru itmek için bir zıplama daha kullanabilir ve bu da oyuncuların havada topa vurmasına izin verir. Oyuncular havadayken arabalarının yönünü değiştirebilir. Oyuncular ayrıca, arabalarının kısa bir sıçrama yapmasına ve belirli bir yönde dönmesine neden olarak, topu dürtmek veya diğer takıma göre konum avantajı elde etmek için kullanılabilecek hızlı kaçışlar gerçekleştirebilirler.\n\n",
    "\tOYNANIŞ HAKKINDAKİ BİLGİLER\n\n"
        "\tPUBG, 100'e yakın oyuncunun büyük ölçekli bir haritada birbirlerini öldürerek hayatta kalmaya çalıştıkları bir ölüm maçı oyunudur. Oyuncular oyuna tek başına, 2 ya da 4 kişilik takımlar hâlinde veya 4 kişilik takımlara karşı tek başına girebilir. Tek başına grup hâlinde girmeyi tercih eden oyuncular rastgele farklı oyuncularla takım olarak eşleştirilir. Her durumda oyuncular oyunu kazanmak için ölmeden en sona kalan oyuncu ya da takım olmaya çalışırlar. Takımdaki tüm oyuncular ölmeden takım dağılmaz. Her maç oyuncular belirli bir rotada ilerleyen uçaklardan istedikleri zaman atlayarak paraşütle 8 x 8 kilometrelik geniş bir haritaya dağılırlar. Oyuncular haritaya indiklerinde oyuna bir etkisi olmayan kişisel kıyafet seçimleri dışında diğer oyunculara karşı üstünlük sağlayacak hiçbir şeyi olmaz. Oyuncular kask, zırh, çanta, silah, bomba, araç gibi çeşitli ekipmanlar bulmak için çeşitli binaları ve alanları ararlar. Zırh, kask, çanta gibi ekipmanlar 3 seviyeye sahiptir. Aynı zamanda silahlar için dürbün, uzatılmış hızlı çekim şarjörü, namlu, susturucu gibi geliştirmeler bulunabilir. Oyuncuların haritanın bazı belirli bölgelerinde daha iyi ekipman ve araçlar bulma ihtimalleri daha fazladır. Her oyuncu daha kaliteli ekipman bulmak istediğinden bu bölgelere daha çok akın ederler ve bu durum bu bölgeleri daha tehlikeli hâle getirir. Seviye arttıkça kapasiteleri ve kaliteleri de artar. Oyunda oyunculara 2 farklı görüş imkânı sunulur isteğe göre oyuncular birinci şahıs veya üçüncü şahıs nişancı modunda oynayabilirler. Oyun esnasında görüş perspektifini değiştirmek mümkündür. Her birkaç dakikada bir harita rastgele bir bölgeye doğru küçülmeye başlar. Haritanın güvenli bölgesine gitmek için oyunculara belirli bir zaman verilir. Zamanında güvenli bölgeye varamayan oyuncular dışarıda kalan tehlikeli bölgeyi yavaşça saran mavi parlayan bir duvar ile karşılaşırlar. Oyuncular güvenli bölgeye ulaşabilmek için çeşitli sağlık paketlerini kullanırlar. Gittikçe daha çok hasar veren bu mavi parıltıdan kurtulamayan oyuncular ölürler. Oyun boyunca kırmızı bölge adı verilen haritanın rastgele belirlenen bir kısmına bomba yağar. Oyuncular bu bombalardan kurtulabilmek için yapıların içine saklanır veya o bölgeden uzaklaşmaya çalışır.\n\n",
    "\tOYNANIŞ HAKKINDAKİ BİLGİLER\n\n"
        "\tMyCareer seiris, mevcut oyun modlarından biri olarak geri dönüyor. MyCareer, oyuncunun kendi özelleştirilebilir basketbol oyuncusunu yarattığı ve basketbol kariyeri boyunca oynadığı bir kariyer modudur. Oyuncular, kadın veya erkek oyuncu yapabilir, ancak kadın yalnızca yeni nesil konsollarda mevcuttur. Mahalle ayrıca oyuncuların gardırobunu özelleştirebileceği, saç kesimi ve dövme yaptırabileceği ve satın alma artışları yapabileceği 2K Beach olarak MyCareer'e geri dönüyor. Ayrıca mevcut takımlarının antrenman tesisinde niteliklerini geliştirmek için antrenmanlarını yapabilir ve alıştırma yapabilirler. MyCareer'deki ilerleme, yalnızca yeni nesil için yapılan bazı değişiklikler nedeniyle nesiller boyunca aktarılamayabilir. Dokuzuncu Nesil DeğişikliklerOyunun yeni nesil sürümünde, The MyCareer çevrimiçi elyafı The Neighbourhood modu, NBA 2K16'dan üyeliklerin geri dönüşüyle ​​The City olarak yeniden markalandı. Oyuncular, Şehre girmek için bir üyelik seçmeden önce benzer şekilde düşük seviyeli oyuncularla oynadıkları Rookieville'de başlar. The City moduna özel seviye sistemi MyRep, tüm MyPlayer yapılarında paylaşılır, bu nedenle oyuncuların tüm karakterleri için Rookieville'den yalnızca bir kez seviye atlamaları gerekir. Bir oyuncu Rookieville'den seviye atladığında, otomatik olarak The City'nin North Side Knights, South City Vipers, Beasts of the East ve Western Wildcats gibi dört üyesinden birine atanır. Oyuncular üyeliklerini değiştirmekte özgürdürler, ancak bunu yaptıkları için seviyeleri Pro 1'e düşürüldükleri için cezalandırılırlar; oyuncunun Rookieville'den ayrıldığı seviyeyle aynı. Oyuncu, üyesi olmadığı üyeliklerde oynayabilse de, MyRep seviyesi için maçlarda kazanılan deneyim miktarını azaltarak ceza vardır. Oyuncular, ünlü basketbolculara karşı tek oyunculu 3v3 oyunlar olan veya The City'deki diğer MyPlayer'lara karşı oyun oynayan NPC'ler tarafından verilen görevlere katılabilirler. Ödüller genellikle Sanal Para Birimi (VC) ve özelleştirmelerdir. Her üyeliğin, genellikle oyun içi, mahkeme tasarımları, oyun içi oynatma listeleri, duvar resimleri tasarımı ve tek tip seçimleri görüntüleyen videolar yapmaktan sorumlu topluluk etkileyicileri olan Belediye Başkanı seçimleri vardır. Her belediye başkanlığı 6 hafta sürer. Oyunumuz, en iyi basketbol takımını kurma ve sanal bir değiş tokuş kartı koleksiyonunu sürdürme fikrine dayanan bir mod olan MyTeam moduna sahiptir. Oyuncular, diğer oyuncuların takımlarına karşı çeşitli formatlarda basketbol turnuvası tarzı yarışmalarda takımlarıyla bir araya gelir ve oynarlar. Bir takımın varlıkları, rastgele kart paketleri ve müzayede evi gibi çeşitli yollarla elde edilir. Sanal Para Birimi (VC), mod içinde yaygın olarak kullanılır. MyTeam'deki ilerleme nesiller boyu devam edecek.\n\n",
  ];
}
